---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-system
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: examples
spec:
  owner: guests
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: example-website
  annotations:
    github.com/project-slug: 'mikeeggertsen/backstage-example'
spec:
  type: website
  lifecycle: experimental
  owner: guests
  system: examples
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-api
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: kong-example
  annotations:
    github.com/project-slug: 'mikeeggertsen/kong-example'
spec:
  type: openapi
  lifecycle: experimental
  owner: guests
  system: examples
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: Kong API Gateway Example
      license:
        name: MIT
    servers:
      - url: http://localhost:8000
    paths:
      /health:
        get:
          summary: Check if service is up
          responses:
            '200': 
              description: Returns OK
              content:
                text/plain
      /hello-world:
        get:
          summary: Get 'Hello World' string
          responses:
            '200':
              description: Returns 'Hello World'
              content:
                text/plain
